# Generated by Django 4.1.4 on 2022-12-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('optional_deadline', models.DateTimeField(blank=True, null=True)),
                ('confirmation', models.BooleanField()),
                ('tags', models.ManyToManyField(related_name='tasks', to='task_service.tags')),
            ],
            options={
                'ordering': ['optional_deadline'],
            },
        ),
    ]
