# Generated by Django 4.1.4 on 2022-12-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_service', '0002_alter_task_datetime_remove_task_tags_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
